kamailio:
  build: kamailio
  net: host
  volumes:
    - ./conf/kamailio.cfg:/etc/kamailio/kamailio.cfg
    - ./conf/kamctlrc:/etc/kamailio/kamctlrc
  ports:
    - "5060:5060/udp"
  command: /run.sh

kamailio_database:
  net: host
  image: mysql:5
  hostname: kamailio_database
  environment:
    - MYSQL_ROOT_PASSWORD=kamailio
  volumes:
    - ./data/mysql:/var/lib/mysql
    - ./conf/mysql_scripts:/docker-entrypoint-initdb.d
