kamailio:
  build: kamailio
#  net: host
  volumes:
    - ./conf/kamailio.cfg:/etc/kamailio/kamailio.cfg
    - ./conf/kamctlrc:/etc/kamailio/kamctlrc
  links:
    - kamailio_database:kamailio_database
    - rtpproxy:rtpproxy
  ports:
    - "5060/udp:5060/udp"
    - "5060:5060"
  command: /run.sh

rtpproxy:
  image: caioquirino/rtpproxy
  hostname: rtpproxy
  expose:
    - "7722/udp"
  command: rtpproxy -F -f -s udp:127.0.0.1:7722 -l 192.168.1.186

kamailio_database:
#  net: host
  image: mysql:5
  hostname: kamailio_database
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=kamailio
  volumes:
    - ./data/mysql:/var/lib/mysql
    - ./conf/mysql_scripts:/docker-entrypoint-initdb.d
